import {
  ProductionListing,
  DemandRequest,
  OrderItem,
  TransportJob,
  Vehicle,
  CropPlan,
  MarketPriceIndex,
  DistrictSupplyMetric,
  VerificationRequest
} from './types';

export const MOCK_PRODUCTIONS: ProductionListing[] = [
  {
    id: 'prod-001',
    listingCode: 'LST-2026-0891',
    farmerName: 'Sunil Bandara',
    farmerPhone: '+94 77 123 4567',
    cropType: 'Keeri Samba Paddy',
    variety: 'BG-360 Premium',
    category: 'Paddy & Rice',
    quantityKg: 4500,
    qualityGrade: 'A',
    harvestDate: '2026-09-22',
    region: 'North Central',
    district: 'Anuradhapura',
    status: 'available',
    minAcceptablePriceKg: 195,
    traditionalFarmgatePriceKg: 160,
    projectedRevenue: 877500,
    description: 'High-moisture-controlled paddy harvested with combine harvester. Cleaned and sun-dried to 13% moisture level.',
    activeAuction: {
      id: 'auc-101',
      openingBid: 195,
      currentHighestBid: 215,
      bidCount: 7,
      endsInMinutes: 45,
      status: 'open',
      highestBidderName: 'Araliya Rice Mills'
    }
  },
  {
    id: 'prod-002',
    listingCode: 'LST-2026-0892',
    farmerName: 'Sunil Bandara',
    farmerPhone: '+94 77 123 4567',
    cropType: 'Dambulla Big Onions',
    variety: 'Rajarata Gold',
    category: 'Vegetables',
    quantityKg: 2800,
    qualityGrade: 'B',
    harvestDate: '2026-09-28',
    region: 'Central',
    district: 'Matale',
    status: 'readyForHarvest',
    minAcceptablePriceKg: 280,
    traditionalFarmgatePriceKg: 220,
    projectedRevenue: 784000,
    description: 'Cured field onions with sound bulbs, sized 50-70mm. Suitable for commercial wholesale storage.',
    activeAuction: {
      id: 'auc-102',
      openingBid: 280,
      currentHighestBid: 305,
      bidCount: 4,
      endsInMinutes: 120,
      status: 'open',
      highestBidderName: 'Keells Food Products'
    }
  },
  {
    id: 'prod-003',
    listingCode: 'LST-2026-0893',
    farmerName: 'Dhammika Perera',
    farmerPhone: '+94 71 889 2233',
    cropType: 'Nuwara Eliya Carrots',
    variety: 'Kuroda Standard',
    category: 'Vegetables',
    quantityKg: 1800,
    qualityGrade: 'A',
    harvestDate: '2026-09-18',
    region: 'Central',
    district: 'Nuwara Eliya',
    status: 'available',
    minAcceptablePriceKg: 340,
    traditionalFarmgatePriceKg: 275,
    projectedRevenue: 612000,
    description: 'Washed and graded high-altitude carrots, uniform orange coloration, crisp and sweet flavor profile.',
    activeAuction: {
      id: 'auc-103',
      openingBid: 340,
      currentHighestBid: 380,
      bidCount: 9,
      endsInMinutes: 18,
      status: 'open',
      highestBidderName: 'Cargills Quality Foods'
    }
  },
  {
    id: 'prod-004',
    listingCode: 'LST-2026-0894',
    farmerName: 'K. Sivalingam',
    farmerPhone: '+94 76 554 1122',
    cropType: 'Jaffna Red Onions',
    variety: 'Vadamarachchi Red',
    category: 'Vegetables',
    quantityKg: 3200,
    qualityGrade: 'A',
    harvestDate: '2026-09-25',
    region: 'Northern',
    district: 'Jaffna',
    status: 'available',
    minAcceptablePriceKg: 420,
    traditionalFarmgatePriceKg: 350,
    projectedRevenue: 1344000,
    description: 'Pungent Jaffna small onions, fully sun-cured with intact dry skins. Prime export or premium retail grade.',
    activeAuction: {
      id: 'auc-104',
      openingBid: 420,
      currentHighestBid: 455,
      bidCount: 6,
      endsInMinutes: 95,
      status: 'open',
      highestBidderName: 'Lanka Agro Traders'
    }
  },
  {
    id: 'prod-005',
    listingCode: 'LST-2026-0895',
    farmerName: 'R. M. Jayawardena',
    farmerPhone: '+94 72 333 4455',
    cropType: 'Welimada Potatoes',
    variety: 'Granola Yellow',
    category: 'Vegetables',
    quantityKg: 5000,
    qualityGrade: 'B',
    harvestDate: '2026-10-04',
    region: 'Uva',
    district: 'Badulla',
    status: 'growing',
    minAcceptablePriceKg: 310,
    traditionalFarmgatePriceKg: 240,
    projectedRevenue: 1550000,
    description: 'Medium to large tubers under active field monitoring. Projected harvest in 2.5 weeks.',
  },
  {
    id: 'prod-006',
    listingCode: 'LST-2026-0896',
    farmerName: 'Sunil Bandara',
    farmerPhone: '+94 77 123 4567',
    cropType: 'Green Chilies',
    variety: 'MI-2 High Spiciness',
    category: 'Spices',
    quantityKg: 650,
    qualityGrade: 'A',
    harvestDate: '2026-09-17',
    region: 'North Central',
    district: 'Anuradhapura',
    status: 'available',
    minAcceptablePriceKg: 680,
    traditionalFarmgatePriceKg: 520,
    projectedRevenue: 442000,
    description: 'Freshly plucked dark green chilies. Crisp texture, suitable for immediate wholesale dispatch.',
    activeAuction: {
      id: 'auc-105',
      openingBid: 680,
      currentHighestBid: 740,
      bidCount: 11,
      endsInMinutes: 32,
      status: 'open',
      highestBidderName: 'Nawaloka Fresh Mart'
    }
  }
];

export const MOCK_DEMANDS: DemandRequest[] = [
  {
    id: 'dem-001',
    buyerName: 'Rohan Jayasuriya',
    buyerCompany: 'Keells Food Products',
    cropType: 'Keeri Samba Paddy',
    quantityNeededKg: 10000,
    fulfilledKg: 4500,
    targetPriceKg: 210,
    deadline: '2026-09-30',
    district: 'Gampaha',
    status: 'open',
    notes: 'Urgent procurement for central mill processing. Moisture must be <= 14%.'
  },
  {
    id: 'dem-002',
    buyerName: 'Chaminda Silva',
    buyerCompany: 'Cargills Agri Procurement',
    cropType: 'Nuwara Eliya Carrots',
    quantityNeededKg: 3500,
    fulfilledKg: 1800,
    targetPriceKg: 375,
    deadline: '2026-09-24',
    district: 'Colombo',
    status: 'open',
    notes: 'Grade A washed carrots needed for island-wide supermarket distribution.'
  },
  {
    id: 'dem-003',
    buyerName: 'F. H. Careem',
    buyerCompany: 'Manning Market Wholesale Consortium',
    cropType: 'Dambulla Big Onions',
    quantityNeededKg: 8000,
    fulfilledKg: 8000,
    targetPriceKg: 300,
    deadline: '2026-09-19',
    district: 'Colombo',
    status: 'fulfilled',
    notes: 'Consignment fully matched from Matale and Galewela clusters.'
  },
  {
    id: 'dem-004',
    buyerName: 'Anura Wickramasinghe',
    buyerCompany: 'Ceylon Fresh Exports Ltd',
    cropType: 'Jaffna Red Onions',
    quantityNeededKg: 5000,
    fulfilledKg: 2200,
    targetPriceKg: 450,
    deadline: '2026-10-05',
    district: 'Jaffna',
    status: 'open',
    notes: 'Air-freight export shipment to Maldives and Singapore. Strictly Grade A.'
  }
];

export const MOCK_ORDERS: OrderItem[] = [
  {
    id: 'ord-1001',
    orderCode: 'ORD-2026-4401',
    cropType: 'Keeri Samba Paddy',
    variety: 'BG-360 Premium',
    quantityKg: 4500,
    pricePerKg: 215,
    totalAmount: 967500,
    farmerName: 'Sunil Bandara',
    buyerName: 'Araliya Rice Mills',
    transporterName: 'Rajarata Express Logistics',
    orderStatus: 'in_transit',
    paymentStatus: 'sandbox_paid',
    deliveryMethod: 'bit_app_transport',
    createdAt: '2026-09-15 09:30',
    pickupLocation: 'Eppawala Farm Gate, Anuradhapura',
    deliveryLocation: 'Araliya Central Mill, Polonnaruwa'
  },
  {
    id: 'ord-1002',
    orderCode: 'ORD-2026-4402',
    cropType: 'Nuwara Eliya Carrots',
    variety: 'Kuroda Standard',
    quantityKg: 1800,
    pricePerKg: 380,
    totalAmount: 684000,
    farmerName: 'Dhammika Perera',
    buyerName: 'Cargills Quality Foods',
    transporterName: 'Upcountry Coldline Logistics',
    orderStatus: 'delivered',
    paymentStatus: 'settled',
    deliveryMethod: 'bit_app_transport',
    createdAt: '2026-09-14 14:15',
    pickupLocation: 'Blackpool Valley, Nuwara Eliya',
    deliveryLocation: 'Cargills Distribution Center, Ja-Ela'
  },
  {
    id: 'ord-1003',
    orderCode: 'ORD-2026-4403',
    cropType: 'Green Chilies',
    variety: 'MI-2 High Spiciness',
    quantityKg: 650,
    pricePerKg: 740,
    totalAmount: 481000,
    farmerName: 'Sunil Bandara',
    buyerName: 'Nawaloka Fresh Mart',
    orderStatus: 'confirmed',
    paymentStatus: 'pending',
    deliveryMethod: 'bit_app_transport',
    createdAt: '2026-09-16 08:45',
    pickupLocation: 'Thalawa Road, Anuradhapura',
    deliveryLocation: 'Nawaloka Warehouse, Peliyagoda'
  },
  {
    id: 'ord-1004',
    orderCode: 'ORD-2026-4404',
    cropType: 'Dambulla Big Onions',
    variety: 'Rajarata Gold',
    quantityKg: 3000,
    pricePerKg: 295,
    totalAmount: 885000,
    farmerName: 'M. Zubair',
    buyerName: 'Keells Food Products',
    transporterName: 'Central Haulage PVT',
    orderStatus: 'disputed',
    paymentStatus: 'sandbox_paid',
    deliveryMethod: 'bit_app_transport',
    createdAt: '2026-09-13 11:20',
    pickupLocation: 'Galewela Outskirts, Matale',
    deliveryLocation: 'Keells Logistics Hub, Kerawalapitiya',
    disputeNotes: 'Buyer reported 180kg outer skin decay caused by heavy rain during loading.'
  }
];

export const MOCK_TRANSPORT_JOBS: TransportJob[] = [
  {
    id: 'tr-801',
    requestCode: 'TRP-2026-091',
    product: 'Keeri Samba Paddy (90 bags)',
    quantityKg: 4500,
    requiredVehicle: 'medium_lorry',
    pickupDistrict: 'Anuradhapura',
    pickupAddress: 'Eppawala Cooperative Depot, Anuradhapura',
    farmerName: 'Sunil Bandara',
    farmerPhone: '+94 77 123 4567',
    deliveryDistrict: 'Polonnaruwa',
    deliveryAddress: 'Araliya Rice Mills, New Town Polonnaruwa',
    buyerName: 'Araliya Rice Mills',
    distanceKm: 82,
    estimatedEarnings: 38500,
    status: 'in_transit',
    driverName: 'Nuwan Gamage',
    vehicleNumber: 'WP-LC-4421',
    updatedAt: '25 mins ago',
    otpCode: '8831'
  },
  {
    id: 'tr-802',
    requestCode: 'TRP-2026-092',
    product: 'Nuwara Eliya Carrots (Crates)',
    quantityKg: 1800,
    requiredVehicle: 'small_lorry',
    pickupDistrict: 'Nuwara Eliya',
    pickupAddress: 'Blackpool Agricultural Center, Nuwara Eliya',
    farmerName: 'Dhammika Perera',
    farmerPhone: '+94 71 889 2233',
    deliveryDistrict: 'Gampaha',
    deliveryAddress: 'Cargills Distribution Center, Ja-Ela',
    buyerName: 'Cargills Quality Foods',
    distanceKm: 146,
    estimatedEarnings: 46200,
    status: 'delivered',
    driverName: 'Thushara Senanayake',
    vehicleNumber: 'CP-DA-9012',
    updatedAt: '2 hours ago',
    otpCode: '4190'
  },
  {
    id: 'tr-803',
    requestCode: 'TRP-2026-093',
    product: 'Green Chilies (Ventilated sacks)',
    quantityKg: 650,
    requiredVehicle: 'pickup',
    pickupDistrict: 'Anuradhapura',
    pickupAddress: 'Thalawa Farmer Center, Anuradhapura',
    farmerName: 'Sunil Bandara',
    farmerPhone: '+94 77 123 4567',
    deliveryDistrict: 'Colombo',
    deliveryAddress: 'Manning Central Market, Peliyagoda',
    buyerName: 'Nawaloka Fresh Mart',
    distanceKm: 198,
    estimatedEarnings: 29800,
    status: 'requested',
    updatedAt: 'Just now'
  },
  {
    id: 'tr-804',
    requestCode: 'TRP-2026-094',
    product: 'Jaffna Red Onions (Mesh bags)',
    quantityKg: 3200,
    requiredVehicle: 'medium_lorry',
    pickupDistrict: 'Jaffna',
    pickupAddress: 'Chavakachcheri Farmer Union, Jaffna',
    farmerName: 'K. Sivalingam',
    farmerPhone: '+94 76 554 1122',
    deliveryDistrict: 'Colombo',
    deliveryAddress: 'Ceylon Fresh Export Air Cargo Terminal, Katunayake',
    buyerName: 'Lanka Agro Traders',
    distanceKm: 385,
    estimatedEarnings: 92400,
    status: 'assigned',
    driverName: 'Kamal Premasiri',
    vehicleNumber: 'WP-LB-1108',
    updatedAt: '40 mins ago',
    otpCode: '6274'
  }
];

export const MOCK_FLEET: Vehicle[] = [
  {
    id: 'veh-01',
    vehicleNumber: 'WP-LC-4421',
    vehicleType: 'medium_lorry',
    capacityKg: 5000,
    status: 'on_trip',
    currentDriver: 'Nuwan Gamage',
    fuelEfficiencyKmPerL: 6.8
  },
  {
    id: 'veh-02',
    vehicleNumber: 'CP-DA-9012',
    vehicleType: 'small_lorry',
    capacityKg: 2500,
    status: 'active',
    currentDriver: 'Thushara Senanayake',
    fuelEfficiencyKmPerL: 8.5
  },
  {
    id: 'veh-03',
    vehicleNumber: 'WP-LB-1108',
    vehicleType: 'medium_lorry',
    capacityKg: 6000,
    status: 'on_trip',
    currentDriver: 'Kamal Premasiri',
    fuelEfficiencyKmPerL: 6.2
  },
  {
    id: 'veh-04',
    vehicleNumber: 'NC-PD-5590',
    vehicleType: 'pickup',
    capacityKg: 1200,
    status: 'active',
    currentDriver: 'Ranga Fernando',
    fuelEfficiencyKmPerL: 11.4
  }
];

export const MOCK_CROP_PLANS: CropPlan[] = [
  {
    id: 'cp-01',
    cropType: 'Keeri Samba Paddy',
    season: 'Maha 2026',
    areaAcres: 3.5,
    expectedYieldKg: 5200,
    district: 'Anuradhapura',
    dsDivision: 'Thalawa',
    status: 'cultivating',
    sowingDate: '2026-05-10',
    harvestTargetDate: '2026-09-22'
  },
  {
    id: 'cp-02',
    cropType: 'Dambulla Big Onions',
    season: 'Yala 2026',
    areaAcres: 1.8,
    expectedYieldKg: 3100,
    district: 'Matale',
    dsDivision: 'Dambulla',
    status: 'cultivating',
    sowingDate: '2026-06-15',
    harvestTargetDate: '2026-09-28'
  },
  {
    id: 'cp-03',
    cropType: 'Sweet Corn',
    season: 'Off-Season',
    areaAcres: 1.0,
    expectedYieldKg: 1800,
    district: 'Anuradhapura',
    dsDivision: 'Thalawa',
    status: 'planned',
    sowingDate: '2026-10-15',
    harvestTargetDate: '2026-12-20'
  }
];

export const MOCK_MARKET_PRICES: MarketPriceIndex[] = [
  {
    id: 'prc-01',
    cropType: 'Keeri Samba Paddy',
    variety: 'BG-360',
    district: 'Anuradhapura',
    grade: 'A',
    currentPriceKg: 215,
    yesterdayPriceKg: 208,
    weeklyHighKg: 220,
    weeklyLowKg: 198,
    source: 'TRANSACTION_DERIVED',
    recordedOn: 'Today, 06:00 AM'
  },
  {
    id: 'prc-02',
    cropType: 'Dambulla Big Onions',
    variety: 'Rajarata Gold',
    district: 'Matale',
    grade: 'A',
    currentPriceKg: 320,
    yesterdayPriceKg: 335,
    weeklyHighKg: 345,
    weeklyLowKg: 290,
    source: 'TRANSACTION_DERIVED',
    recordedOn: 'Today, 06:00 AM'
  },
  {
    id: 'prc-03',
    cropType: 'Nuwara Eliya Carrots',
    variety: 'Kuroda',
    district: 'Nuwara Eliya',
    grade: 'A',
    currentPriceKg: 385,
    yesterdayPriceKg: 360,
    weeklyHighKg: 390,
    weeklyLowKg: 330,
    source: 'TRANSACTION_DERIVED',
    recordedOn: 'Today, 06:00 AM'
  },
  {
    id: 'prc-04',
    cropType: 'Jaffna Red Onions',
    variety: 'Local Red',
    district: 'Jaffna',
    grade: 'A',
    currentPriceKg: 460,
    yesterdayPriceKg: 450,
    weeklyHighKg: 480,
    weeklyLowKg: 420,
    source: 'TRANSACTION_DERIVED',
    recordedOn: 'Today, 06:00 AM'
  },
  {
    id: 'prc-05',
    cropType: 'Welimada Potatoes',
    variety: 'Granola',
    district: 'Badulla',
    grade: 'B',
    currentPriceKg: 310,
    yesterdayPriceKg: 310,
    weeklyHighKg: 325,
    weeklyLowKg: 295,
    source: 'DEMO_SEED',
    recordedOn: 'Yesterday'
  },
  {
    id: 'prc-06',
    cropType: 'Green Chilies',
    variety: 'MI-2',
    district: 'Dambulla / Matale',
    grade: 'A',
    currentPriceKg: 730,
    yesterdayPriceKg: 690,
    weeklyHighKg: 760,
    weeklyLowKg: 640,
    source: 'TRANSACTION_DERIVED',
    recordedOn: 'Today, 06:00 AM'
  }
];

export const MOCK_DISTRICT_SUPPLY: DistrictSupplyMetric[] = [
  {
    district: 'Anuradhapura',
    province: 'North Central',
    majorCrops: ['Paddy', 'Chilies', 'Maize', 'Soybean'],
    totalCultivatedAcres: 48200,
    projectedHarvestTonnes: 92400,
    activeFarmers: 14250,
    marketDemandTonnes: 78000,
    supplyDeficitSurplusTonnes: 14400 // Healthy Surplus
  },
  {
    district: 'Nuwara Eliya',
    province: 'Central',
    majorCrops: ['Carrots', 'Leeks', 'Potatoes', 'Cabbage'],
    totalCultivatedAcres: 16400,
    projectedHarvestTonnes: 34200,
    activeFarmers: 8920,
    marketDemandTonnes: 38000,
    supplyDeficitSurplusTonnes: -3800 // Mild Deficit
  },
  {
    district: 'Matale (Dambulla)',
    province: 'Central',
    majorCrops: ['Big Onions', 'Tomatoes', 'Green Chilies'],
    totalCultivatedAcres: 22800,
    projectedHarvestTonnes: 45600,
    activeFarmers: 11400,
    marketDemandTonnes: 41200,
    supplyDeficitSurplusTonnes: 4400 // Surplus
  },
  {
    district: 'Jaffna',
    province: 'Northern',
    majorCrops: ['Red Onions', 'Grapes', 'Cassava', 'Banana'],
    totalCultivatedAcres: 14100,
    projectedHarvestTonnes: 26800,
    activeFarmers: 7350,
    marketDemandTonnes: 24500,
    supplyDeficitSurplusTonnes: 2300 // Exportable Surplus
  },
  {
    district: 'Badulla (Welimada)',
    province: 'Uva',
    majorCrops: ['Potatoes', 'Beans', 'Cabbage', 'Beetroot'],
    totalCultivatedAcres: 19800,
    projectedHarvestTonnes: 37500,
    activeFarmers: 9800,
    marketDemandTonnes: 40100,
    supplyDeficitSurplusTonnes: -2600 // Moderate Deficit
  },
  {
    district: 'Colombo & Western Hub',
    province: 'Western',
    majorCrops: ['Urban Consumption Hub', 'Leafy Greens'],
    totalCultivatedAcres: 2100,
    projectedHarvestTonnes: 4200,
    activeFarmers: 1200,
    marketDemandTonnes: 89000,
    supplyDeficitSurplusTonnes: -84800 // Major Consumer Center
  }
];

export const MOCK_VERIFICATIONS: VerificationRequest[] = [
  {
    id: 'ver-101',
    applicantName: 'Rohan Jayasuriya',
    applicantRole: 'buyer',
    organizationName: 'Keells Food Products PLC',
    brnOrNic: 'PV-18920-LK',
    district: 'Colombo',
    submittedAt: '2026-09-15',
    documents: ['BRN Certificate.pdf', 'Tax Clearance 2025.pdf'],
    status: 'pending'
  },
  {
    id: 'ver-102',
    applicantName: 'Priyashantha Silva',
    applicantRole: 'transporter',
    organizationName: 'Rajarata Express Logistics',
    brnOrNic: 'WC-99412-TR',
    district: 'Anuradhapura',
    submittedAt: '2026-09-14',
    documents: ['Goods Carriage License.pdf', 'Fleet Insurance Cover.pdf'],
    status: 'approved'
  },
  {
    id: 'ver-103',
    applicantName: 'M. H. M. Nazeer',
    applicantRole: 'buyer',
    organizationName: 'Lanka Agro Traders Wholesale',
    brnOrNic: 'SP-44218-TR',
    district: 'Kandy',
    submittedAt: '2026-09-16',
    documents: ['Business Registration.pdf'],
    status: 'pending'
  }
];
